package org.example.dao;

import java.io.PrintStream;
import java.util.ResourceBundle;

public final class TestConstant {
    private static final ResourceBundle RESOURCE_BUNDLE
            = ResourceBundle.getBundle("database");
    public static final String JDBC_URL = RESOURCE_BUNDLE.getString("test.url");
    public static final String USER = RESOURCE_BUNDLE.getString("test.user");
    public static final String PASSWORD = RESOURCE_BUNDLE.getString(
            "test.password");

    public static final String CREATE_PERSON_TABLE_SQL
            = "CREATE TABLE person (id INTEGER GENERATED BY DEFAULT AS IDENTITY, name VARCHAR(255) NOT NULL, surname VARCHAR(255) NOT NULL, CONSTRAINT PK_person PRIMARY KEY (id))";

    public static final String DELETE_PERSON_TABLE_SQL = "DROP TABLE person";
    public static final String SELECT_PERSON_BY_ID_SQL
            = "SELECT id, name, surname FROM person WHERE id = ?";

    public static final String ID_COLUMN_TITLE = "id";
    public static final String NAME_COLUMN_TITLE = "name";
    public static final String SURNAME_COLUMN_TITLE = "surname";
    public static final String CARRIAGE_RETURN = "\r";
    public static final String STRING_RETURN = "\n";
    public static final String TABULATION = "\t";
    public static final PrintStream ORIGINAL_OUT = System.out;

    private TestConstant() {
    }
}
